### ISSUE TITLE
S3 endpoint URI invalid (independent of region issue)

### ISSUE THREAD

**Issue by yukatherin** [databricks/spark-redshift#135]
Hi, I'm having this issue, which is causing my program to fail. It could still be something wrong on my side but @JoshRosen asked me to start an issue.

<pre>
App > java.lang.IllegalArgumentException: Invalid S3 URI: hostname does not appear to be a valid S3 endpoint: s3://kyu/temp/testcopy
App > 	at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:65)
App > 	at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:42)
App > 	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:90)
App > 	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:362)
App > 	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
App > 	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
App > 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
App > 	at KeywordMapping$.execute(KeywordMapping.scala:50)
App > 	at KeywordMappingJob$.main(KeywordMappingJob.scala:11)
App > 	at KeywordMappingJob.main(KeywordMappingJob.scala)
App > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
App > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
App > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
App > 	at java.lang.reflect.Method.invoke(Method.java:606)
App > 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:700)
App > 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:183)
App > 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:208)
App > 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:123)
App > 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
App > 15/12/07 18:13:00 sparkDriver-akka.actor.default-dispatcher-16 INFO BlockManagerMasterEndpoint: Registering block manager ip-172-31-33-34.ec2.internal:53290 with 8.6 GB RAM, BlockManagerId(4, ip-172-31-33-34.ec2.internal, 53290)
App > 15/12/07 18:13:00 main WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
App > java.lang.IllegalArgumentException: Invalid S3 URI: hostname does not appear to be a valid S3 endpoint: s3://kyu/temp
</pre>

I'm using aws-java-sdk-core 1.10.22. 

I see how my URI causes an error here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java

I've tried different versions of the endpoint URI to match the reg ex. I am wondering how your example works - maybe I'm making a mistake which would lead to an addition in the docs.

(Also, see this, but it doesn't seem to be relevant: https://forums.databricks.com/questions/1963/why-spark-redshift-can-not-write-s3-bucket.html)
Thank you for any help.

**Comment by JoshRosen** [comment]
Sorry for the long delay in investigating this. Digging into the stacktrace a little, I'm a bit confused by what appears to be a mismatch between the line numbers in your stacktrace and the AWS SDK version that you said you are using. In 1.10.22, it looks like line 65 of AmazonS3URI does not correspond to the line that's throwing the IllegalStateException:

https://github.com/aws/aws-sdk-java/blob/1.10.22/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java#L65

However, that line _does_ seem to match up in much earlier versions of the SDK, such as 1.7.13: https://github.com/aws/aws-sdk-java/blob/1.7.x/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java#L65

Maybe an older version of the SDK is taking precedence on your classpath?

If you did want to try to make things work with this older SDK, it appears that these old versions require you to specify an explicit endpoint (see the [list of S3 endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) to find the correct endpoint for the AWS region containing your bucket).

For example, if your `kyu` bucket is hosted in US East (N. Virginia), I think you might be able to use `s3://s3.amazonaws.com/kyu/temp/testcopy` as your `tempdir`. However, I don't think that this pattern will work with newer versions of the SDK since they'll interpret the first component after the `s3://` as the bucket name.

I'm not sure whether `spark-redshift` itself supports the 1.7.x versions of the AWS Java SDK. They might happen to work, but this hasn't been tested. If there's interest in explicit support for those versions, I would be willing to code-review a patch which added integration tests for those versions, but I don't have time to work on such a patch myself.

**Comment by JoshRosen** [comment]
Ping @yukatherin, any updates here? Did you ever get a chance to look into the AWS SDK classpath precedence issues?

**Comment by yukatherin** [comment]
@JoshRosen No, sorry. I had limited time so I just worked around it with a postgres driver and an Unload  command. I have tried s3://s3.amazonaws.com/kyu/temp/testcopy before but I can't remember the exact error. Will try again soon.

Thank you very much for your help - I really appreciate it.

**Comment by JoshRosen** [comment]
Ah, okay; thanks for reporting back. I'm going to close this issue for now in order to de-clutter the open issues list.

If you (or anyone else) sees these symptoms again and would like to take a shot at debugging them, either re-open this ticket or file a new one. Thanks!

**Comment by sonya** [comment]
I just ran into this, so I thought I'd write an explanation in case it helps anyone.

If you have Spark loading Hadoop libraries independent of your project, i.e. through the `spark.*.extraClassPath` configs, this will cause Hadoop to load its own copy of the aws sdk, which is `aws-java-sdk-1.7.4.jar` for the current Hadoop version. (An updated dependency should be available in [upcoming releases](https://issues.apache.org/jira/browse/HADOOP-12269).)

I had set the `extraClassPath` configs based on what several stackoverflow answers said, but I think `extraClassPath` is not generally meant to be used that way. What worked for me was adding this to `build.sbt` (obviously the aws sdk version doesn't have to be exactly 1.10.71, it just needs to be something that doesn't conflict with hadoop or databricks):

```
libraryDependencies += "com.amazonaws" % "aws-java-sdk-core" % "1.10.71"
libraryDependencies += "com.amazonaws" % "aws-java-sdk-s3"   % "1.10.71"

libraryDependencies += "org.apache.hadoop" % "hadoop-aws" % "2.7.2" excludeAll(
  ExclusionRule("com.amazonaws","aws-java-sdk"),
  ExclusionRule("commons-collections","commons-collections"),
  ExclusionRule("commons-beanutils","commons-beanutils")
)
```

Note that you won't be able to use the `s3a` URI scheme as Hadoop's filesystem code will try to call a method that no longer exists in the AWS SDK.

**Comment by Antobiotics** [comment]
Hi, I'm running into that exact same issue and can't get my hands around it, it's probably something silly.
I'm using `spark-1.6.0` with `hadoop-2.6` with `aws-java-sdk-1.7.4` and `hadoop-aws-2.6.0` and 
`spark-redshift_2.10:0.6.0`, which gets me to that error:

```
Invalid S3 URI: hostname does not appear to be a valid S3 endpoint: s3://temp-bucket/spark-tmp
	at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:65)
	at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:42)
...
```
The weird thing is that when i check my bucket the temporary data __does exist__.

I have tried several combinations dependencies with  `aws-java-sdk-1.10.75` and `hadoop-aws-2.7.2` but got an other error: `Provider org.apache.hadoop.fs.s3a.S3AFileSystem could not be instantiated`

Do you have encountered similar issues? Is there something obvious that i missed?

Anyway thank you very much for that great package.

**Comment by shibatako** [comment]
👍

**Comment by robbyki** [comment]
Any update on this. don't see any solutions that worked with anyone on this thread. I've tried all options mentioned as well with no luck.

**Comment by JoshRosen** [comment]
One common denominator in two of these error reports is that this problem affected users running version 1.7.4 of the AWS Java SDK. Looking through the forks of `spark-redshift`, I found a patch (https://github.com/jameshou/spark-redshift/commit/dc9aa505008af0a74c446cbf475302fc4a494018) in @jameshou's fork which seems to be replacing bucket-names with full hostnames (e.g. `bucket.s3.amazonaws.com` instead of `bucket`).

I'd be interested in seeing whether we can reproduce this issue using this library's own integration tests if we use the 1.7.4 version of the AWS SDK and also to see whether some version of the change in @jameshou's patch fixes this issue.

**Comment by JoshRosen** [comment]
Yep, just confirmed that https://github.com/aws/aws-sdk-java/pull/243 is not present in version 1.7.4 of the SDK, so I think you'll have to use `mybucketname.some.s3.endpoint.com/path/path/...` as your URI. @robbyki, could you give that a try and report back whether it works?

**Comment by robbyki** [comment]
Yeah. No luck after trying that different endpoint format to comply with older sdk. As I understand what's been stated so far, spark-redshift protocol only works with latest version of sdk 1.10.x which I can confirm after successfully testing in intellij and pulling in dependencies with maven but now spending time trying to get spark-submit to work and similar to @Antobiotics has mentioned, I've tried updating my sdk in hadoop libs but obviously that breaks my hadoop and pointing spark to the newer sdk through extraClassPath method doesn't work either since it will still default to the sdk provided by my hadoop which is 1.7.4. Ideally, now I'm trying to figure out how to just make it so that my hadoop uses the latest sdk 1.11.15 but still trying to understand if that is even available yet (https://issues.apache.org/jira/browse/HADOOP-12269)

**Comment by JoshRosen** [comment]
One slightly ugly workaround would be to shade the AWS Java SDK and `spark-redshift` in order to avoid conflicts with your Hadoop's provided versions of those dependencies.

**Comment by JoshRosen** [comment]
I found two easy ways to fix this, by the way:

1. Inline the newest version of `AmazonS3URI` into `spark-redshift`. This will work because we only use `AmazonS3URI` for parsing the bucket and path components of URIs, so changing the package name for that class won't break anything. That code also happens to be Apache 2.0 licensed, so its license should be compatible with inlining the code here (provided copyright headers are preserved, etc.).
2. Write our own code for validating / parsing these URIs.

It turns out that a URI like `s3://mybucket.s3.amazonaws.com/path` will cause other problems when dealing with manifests and paths in Redshift, since Redshift expects the `s3://` URI to **not** include an explicit endpoint and will produce URIs which lack that endpoint.

If you're interested in working on either of these approaches, I'd be happy to review a PR. I lean towards the first since it's simple and easy to test.

**Comment by robbyki** [comment]
Thank you. Would like to just get this to work based on whatever configuration is recommended instead of doing too much hacking right now. What is the recommended setup that this has been tested with? What are the configurations, s3 uri scheme and formats that people are having success with? Just want to run a very simple standalone scala app to read a small table from redshift into a dataframe. I'm willing to adjust my versions and libraries as needed but still don't understand what exact configuration I need.

**Comment by miha93** [comment]
when running with aws-java-sdk 1.11.9 and hadoop-aws 2.6.4 on spark 1.6 and hadoop 2.6 I get the following error message
py4j.protocol.Py4JJavaError: An error occurred while calling o36.showString.
: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:87)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:253)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:145)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:407)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:387)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:369)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:341)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:323)
        at com.databricks.spark.redshift.DefaultSource$$anonfun$$init$$1.apply(DefaultSource.scala:39)
        at com.databricks.spark.redshift.DefaultSource$$anonfun$$init$$1.apply(DefaultSource.scala:39)
        at com.databricks.spark.redshift.RedshiftRelation.buildScan(RedshiftRelation.scala:93)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:57)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:57)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:292)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:291)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:370)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:287)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:53)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
        at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:349)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
        at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:47)
        at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:45)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:52)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:52)
        at org.apache.spark.sql.DataFrame.withCallback(DataFrame.scala:2095)
        at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1374)
        at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1456)
        at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

**Comment by blrnw3** [comment]
Happens to me too using `--packages=com.databricks:spark-redshift_2.10:0.6.0,com.databricks:spark-avro_2.10:2.0.1,com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.1`

If i have time i'll submit a PR

**Comment by cfrancocapo** [comment]
Hi,
Any update about the issue?

**Comment by robbyki** [comment]
I was able to fix this by just using the latest aws-java-sdk and putting the jar on my spark class path to replace the 1.7.4 version that came with my hadoop. Have you tried that?

**Comment by JoshRosen** [comment]
Yeah, using a newer version of the AWS Java SDK is known to fix this issue. As I [commented upthread](https://github.com/databricks/spark-redshift/issues/135#issuecomment-232193103), it may be possible to patch `spark-redshift` to add compatibility with older versions of the AWS Java SDK; patches are welcome for this and I'd be glad to review any changes in this direction as long as they're accompanied by tests.

**Comment by cfrancocapo** [comment]
Hi,
The issue is about: 

java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56)

spark: 1.6.1
databricks: 1.0.0
aws-java-sdk-core: 1.11.23

How did you fix it?

Thanks!

**Comment by robbyki** [comment]
Can you verify that you have the `httpcore-4.4.4.jar` and `httpclient-4.5.2.jar` available on your classpath also? That might fix the issue. http://stackoverflow.com/questions/37979097/nosuchmethoderror-org-apache-http-conn-ssl-sslconnectionsocketfactory

**Comment by cfrancocapo** [comment]
Hi,
Yes, httpcore-4.4.5 and httpclient-4.5.2 are included in the classpath. Any other idea?

**Comment by nimmicv** [comment]
I am also running into the same error.

**Comment by JoshRosen** [comment]
#254, which I merged yesterday, should address this issue.

**Comment by blrnw3** [comment]
Many thanks for fixing this.
Looking forward to seeing it in the 1.x branch!

**Comment by cfrancocapo** [comment]
Thanks, when do you plan to release the new version with the fix?

**Comment by JoshRosen** [comment]
@cfrancocapo, I have published [version 2.0.1](https://github.com/databricks/spark-redshift/releases/tag/v2.0.1) of this library to Maven Central and should have it up on spark-packages.org shortly as well.

I'll try to get the 1.x backport turned around soon, too.

**Comment by JoshRosen** [comment]
I have just pushed release 1.1.0 to Maven Central, so I'm going to mark this issue as resolved.

Spark 1.x users who want this fix should use version 1.1.0 or higher of this library, while Spark 2.0 users should use version 2.0.1 or higher.

**Comment by cfrancocapo** [comment]
I am still getting the same issue even with updated lib to 1.1.0 :(

**Comment by blrnw3** [comment]
Working perfectly for me. Thanks for your efforts, Josh
FYI I'm using pyspark with `--packages=om.databricks:spark-redshift_2.10:1.1.0,com.databricks:spark-avro_2.10:2.0.1,org.apache.hadoop:hadoop-aws:2.7.1`

**Comment by JoshRosen** [comment]
@cfrancocapo, can you please open a new GitHub issue for the problems that you're experiencing? Based on your earlier comment, I think that they might have a different root cause, so I want to fork the discussion to help keep things organized. Thanks!

**Comment by Aung-Myint-Thein** [comment]
@blrnw3 If you update the spark-redshift to spark-redshift_2.10-2.0.1.jar , it should be solved. :)
